### ISSUE TITLE
page_20

### ISSUE THREAD

**Issue by TDL77** [GlxbX/kinopoisk_parser#1]
Добрый день . 
запустил скрипт и в top1000.json , записывает только 20 (последнюю страницу ) из
https://www.kinopoisk.ru/lists/movies/top_1000/?page=20
Подскажите как сделать чтобы парсил все страницы с 1 по 20 ?

**Comment by GlxbX** [comment]
Добрый.
Был косяк с многопоточностью, залил стабильную версию без нее.

**Comment by TDL77** [comment]
line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55c6a2e37fb3 <unknown>
#1 0x55c6a2b0b4a7 <unknown>
#2 0x55c6a2b52dd6 <unknown>
#3 0x55c6a2b52ec1 <unknown>
#4 0x55c6a2b90354 <unknown>
#5 0x55c6a2b7496d <unknown>
#6 0x55c6a2b8dc02 <unknown>
#7 0x55c6a2b74713 <unknown>
#8 0x55c6a2b4718b <unknown>
#9 0x55c6a2b47f7e <unknown>
#10 0x55c6a2dfd8d8 <unknown>
#11 0x55c6a2e01800 <unknown>
#12 0x55c6a2e0bcfc <unknown>
#13 0x55c6a2e02418 <unknown>
#14 0x55c6a2dcf42f <unknown>
#15 0x55c6a2e264e8 <unknown>
#16 0x55c6a2e266b4 <unknown>
#17 0x55c6a2e37143 <unknown>
#18 0x7f13ad894ac3 <unknown>
